name: Deploy to Production

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allow manual triggers

env:
  NODE_VERSION: '20'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: |
            app/package-lock.json
            marketing/package-lock.json

      # Build API
      - name: Install API dependencies
        working-directory: ./app
        run: npm ci --production

      - name: Generate Prisma Client
        working-directory: ./app
        run: npx prisma generate

      # Build Marketing Site
      - name: Install Marketing dependencies
        working-directory: ./marketing
        run: npm ci

      - name: Build Marketing site
        working-directory: ./marketing
        run: npm run build
        env:
          NODE_ENV: production

      # Prepare deployment package
      - name: Prepare deployment artifacts
        run: |
          # Create deployment directory
          mkdir -p deploy-package
          
          # Copy API files (excluding node_modules)
          rsync -av --exclude='node_modules' \
                    --exclude='.env' \
                    --exclude='*.log' \
                    app/ deploy-package/app/
          
          # Copy only production dependencies for API
          cd app
          npm ci --production --prefix ../deploy-package/app
          cd ..
          
          # Copy Prisma files for migrations
          cp -r app/prisma deploy-package/app/
          
          # Copy Marketing built files
          mkdir -p deploy-package/marketing
          
          # Debug: Check what Next.js build created
          echo "Checking Next.js build output..."
          ls -la marketing/.next/ | head -20
          
          # Check if standalone build exists (from next.config.mjs output: 'standalone')
          if [ -d "marketing/.next/standalone" ]; then
            echo "✅ Found Next.js standalone build"
            echo "Contents of standalone directory:"
            ls -la marketing/.next/standalone/ | head -10
            
            # Copy standalone files to root of marketing deploy folder
            # This is how Next.js expects standalone to be deployed
            cp -r marketing/.next/standalone/* deploy-package/marketing/
            
            # Copy static files and public separately (required for standalone)
            mkdir -p deploy-package/marketing/.next
            cp -r marketing/.next/static deploy-package/marketing/.next/
            cp -r marketing/public deploy-package/marketing/ 2>/dev/null || true
            
            echo "Verifying standalone deployment structure:"
            ls -la deploy-package/marketing/ | head -10
            echo "Checking for server.js:"
            find deploy-package/marketing -name "server.js" -type f | head -5
          else
            echo "⚠️ WARNING: No standalone build found!"
            echo "Next.js 15 may have issues with standalone mode."
            echo "Using full build with production dependencies..."
            
            # Copy full Next.js build
            cp -r marketing/.next deploy-package/marketing/
            cp -r marketing/public deploy-package/marketing/ 2>/dev/null || true
            cp marketing/package*.json deploy-package/marketing/
            
            # Install ONLY production dependencies locally and copy
            echo "Installing production dependencies for deployment..."
            mkdir -p temp-marketing
            cp marketing/package*.json temp-marketing/
            cd temp-marketing
            # Install with --omit=dev for production only
            npm ci --omit=dev
            cd ..
            
            # Copy the production node_modules
            cp -r temp-marketing/node_modules deploy-package/marketing/
            rm -rf temp-marketing
            
            echo "Deployment package includes node_modules for marketing"
            echo "Size of marketing deployment:"
            du -sh deploy-package/marketing/
          fi
          
          # Copy deployment script
          cp scripts/deploy-remote.sh deploy-package/ 2>/dev/null || true

      # Setup SSH
      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DO_SSH_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          ssh-keyscan -H ${{ secrets.DO_HOST }} >> ~/.ssh/known_hosts

      # Deploy to server
      - name: Deploy to Digital Ocean
        run: |
          # Create tar archive of deployment package
          echo "Creating deployment archive..."
          tar -czf deploy-package.tar.gz deploy-package/
          
          # Show archive size for debugging
          ls -lh deploy-package.tar.gz
          
          # Transfer the single compressed file to server
          echo "Transferring deployment archive to server..."
          scp -i ~/.ssh/deploy_key deploy-package.tar.gz \
              ${{ secrets.DO_USER }}@${{ secrets.DO_HOST }}:/home/trivia/
          
          # Extract and deploy on server
          echo "Extracting and deploying on server..."
          ssh -i ~/.ssh/deploy_key ${{ secrets.DO_USER }}@${{ secrets.DO_HOST }} \
            "cd /home/trivia && \
             rm -rf trivia-engine-deploy && \
             tar -xzf deploy-package.tar.gz && \
             cd deploy-package && \
             export DATABASE_URL='${{ secrets.DATABASE_URL }}' && \
             export JWT_SECRET='${{ secrets.JWT_SECRET }}' && \
             export PORT=3003 && \
             bash deploy-remote.sh && \
             cd .. && \
             rm -f deploy-package.tar.gz"

      # Run database migrations
      - name: Run database migrations
        run: |
          ssh -i ~/.ssh/deploy_key ${{ secrets.DO_USER }}@${{ secrets.DO_HOST }} \
            "cd /home/trivia/trivia-engine/app && \
             export DATABASE_URL='${{ secrets.DATABASE_URL }}' && \
             npx prisma migrate deploy"

      # Restart services
      - name: Restart PM2 services
        run: |
          ssh -i ~/.ssh/deploy_key ${{ secrets.DO_USER }}@${{ secrets.DO_HOST }} \
            "pm2 restart api marketing && pm2 save"

      # Health check
      - name: Health check
        run: |
          sleep 10
          # Check API health
          curl -f https://api.trivia-engine.com/api/health || exit 1
          # Check marketing site
          curl -f https://trivia-engine.com || exit 1

      # Cleanup
      - name: Cleanup SSH
        if: always()
        run: rm -f ~/.ssh/deploy_key

  notify:
    needs: build-and-deploy
    runs-on: ubuntu-latest
    if: always()
    
    steps:
      - name: Notify deployment status
        run: |
          if [ "${{ needs.build-and-deploy.result }}" == "success" ]; then
            echo "✅ Deployment successful!"
          else
            echo "❌ Deployment failed!"
          fi